### ISSUE TITLE
Add trilium-ios-shortcut

### ISSUE THREAD

**Issue by meichthys** [Nriver/awesome-trilium#12]
I'm not really sure which section this would belong under, but it seems to be worth including:
https://github.com/soulsands/trilium-ios-shortcut

**Comment by Nriver** [comment]
I'm considering add a `mobile` section with `Android` and `iOS` sub-sections to hold mobile related stuff.

**Comment by Nriver** [comment]
Ok，I've made some change. [add mobile section](https://github.com/Nriver/awesome-trilium/commit/a155a4a7a6f09f73750dda9e20afa4a12f450047)
