### ISSUE TITLE
New Theme

### ISSUE THREAD

**Issue by Ivy-End** [Nriver/awesome-trilium#22]
I have made a new theme for trilium named [Mist-Moon](https://github.com/Ivy-End/Mist-Moon).

**Comment by Nriver** [comment]
Please, feel free to make a pr.

**Comment by Ivy-End** [comment]
Sorry, I don't know how to pr, could you do me a favour to add this theme, thanks.

here is the content:

[Mist-Moon](https://github.com/Ivy-End/Mist-Moon) A Light Theme inspired by mist moon night view.

**Comment by Nriver** [comment]
Sure thing. Done.
