### ISSUE TITLE
Category for trilium-types?

### ISSUE THREAD

**Issue by rauenzi** [Nriver/awesome-trilium#29]
I created a [`types` package for Trilium](https://github.com/rauenzi/trilium-types) for developing both frontend and backend scripts. For TypeScript development this adds full typed support, and for JavaScript development, it adds type hints, autocomplete, and more.

I'm just not sure what category it really fits into here or if it should even be included at all since it's more niche and for developers than users.

**Comment by Nriver** [comment]
May be a `Development Tools` section would be suitable. You can put it some where around the `ETAPI` section as they are for developers.

**Comment by QuentinLeCaignec** [comment]
A `Devtools` or `Development Tools` section could be useful, as the API and general tooling of trilium matures and stabilizes I think we might genuinely have more entries in there.
If there ever is a simplified flow for making, bundling, finding and installing plugins/widgets/themes/etc for trilium, many neat little programs will probably be released.
