### ISSUE TITLE
Add descriptions to readme headings

### ISSUE THREAD

**Issue by meichthys** [Nriver/awesome-trilium#35]
Could we add descriptions to the readme headings? 
I struggle to come up with a clear distinction between scripts/widgets/extensions/api extensions.

**Comment by Nriver** [comment]
Sorry for the late reply. I had been diagnosed with lumbar disc herniation and stayed in the hospital for a while.

Just added some desctiptions and rearranged some items  b96457cf3d6d6f16c904dc26c3134c8eb40b0772. Hope it's getting clearer than before.
